run_identifier: 'practise_clip_lr_increase_2e-4_acc_flush_2'
logdir: 'Log_Results'
wandb_params:
  mode: 'online' # seeing if it will reduce overhead 
  entity: 'sanazkazeminia97'
  project: 'refactored_prism'
dataset: 'crossdock'
datadir: 'data'
enable_progress_bar: False
num_sanity_val_steps: 0
batch_size: 10 # number of pockets to sample for (60)
lr: 1.0e-6 
num_workers: 8 # suggested by terminal for better parallelisations ???
gpus: 1
n_epochs: 1 # lightnings epoch which defines outer epochs using train_dataset size. Leave as 1

mode: 'pocket_conditioning'
pocket_representation: 'full-atom'

augment_noise: 0
augment_rotation: False
clip_grad: True
auxiliary_loss: False
loss_params:
  max_weight: 0.001
  schedule: 'linear'
  clamp_lj: 3.0

ppo_params:
  num_outer_epochs: 200      # num of PPO cycles (outer epochs)
  num_inner_epochs: 3        # Updates per rollout (inner epochs) (4) - SHOULD BE DYNAMICALLY CONTROLLED
  n_steps: 30             # Rollout length (mols generated) (prev. gen batch size) (60)
  ligand_chunk_size: 10
  ppo_batch_size: 5      # Size of each PPO update batch (20)
  clip_range: 0.2           # PPO clipping parameter temp 0.01
  value_loss_coef: 0.0        # Weight for value loss
  entropy_coef: 0.000           # Weight for entropy bonus not in use
  max_grad_norm: 1.0             # Gradient clipping threshold
  gradient_accumulation_steps: 126   # accumulate over train_timesteps
  num_train_timesteps: 126
  gae_lambda: 0.95            # GAE smoothing factor
  gamma: 0.99                 # Discount factor
  num_mini_batches: 1        # Mini-batches per update (3?) - dyanmic calc
  target_kl: 0.03            # Early stopping KL divergence -
  lr: 2.0e-5                 # Optimizer learning rate - changed from 3e-5 
  mol_timeout_sec: 60
  num_nodes_lig: 25 # fixed number of nodes for ligand
  top_k: False
  # backward progressive training https://arxiv.org/pdf/2503.11240  
  # https://github.com/hu-zijing/B2-DiffuRL/blob/main/run_train.py
  progressive_training: True
  start_timesteps: 50
  end_timesteps: 350
  progressive_training_epochs: 100 # should be same as num_outer_epochs really
  

#  (from diffsbdd original config)
egnn_params:
  device: 'cuda'
  edge_cutoff_ligand: null
  edge_cutoff_pocket: 5.0
  edge_cutoff_interaction: 5.0
  reflection_equivariant: False
  joint_nf: 32
  hidden_nf: 128 # change back to 256
  n_layers: 5
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100

diffusion_params:
  diffusion_steps: 500
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 5.0e-4
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 4]

fp16: False

eval_epochs: 10
visualize_sample_epoch: 99999
visualize_chain_epoch: 999999
eval_params:
  n_eval_samples: 20
  eval_batch_size: 20
  smiles_file: 'data/train_smiles.npy'
  n_visualize_samples: 10
  keep_frames: 5
